### ISSUE TITLE
Doesn't seem to be a way to make all builds on my server not-private

### ISSUE THREAD

**Issue by elsigh** [bslatkin/dpxdt#140]
I'm using organizational auth but all builds seem private. I can just add everyone on my team to each build, but there's a string next to my build that says "private" which makes me wonder if I'm missing something?

**Comment by bslatkin** [comment]
How does the organizational auth stuff work?
How many builds do you have?

Seems like a good idea in general. It's in this attribute:

https://github.com/bslatkin/dpxdt/blob/master/dpxdt/server/models.py#L99

Which is used here:

https://github.com/bslatkin/dpxdt/blob/master/dpxdt/server/auth.py#L222

I guess you could add a new config parameter on "app" like IGNORE_AUTH that you use to override the auth check?

**Comment by elsigh** [comment]
On GAE I have it set to do domain-level auth for access in any capacity to my-company-server.appspot.com, so I just want anyone in my company to be able to see everything in our dpxdt service without having to explicitly add them as an admin.

The public attribute looks good to me, I just don't see a way to configure it. Happy to add that if that makes sense..

**Comment by bslatkin** [comment]
Gotcha. Yeah there's no way to configure that. You'd have to add a new parameter. Sounds like a good idea. With that type of Auth can you still allow completely public resources? I'm wondering how your worker is going to talk to the API server, since it's not going through a Google account login, ya know?

**Comment by elsigh** [comment]
Somehow it already works (my worker has access via the Dev Console) so making my builds public shouldn't make it worse..

**Comment by bslatkin** [comment]
Great. Sounds straight forward. That function in auth.py should do it.

**Comment by elsigh** [comment]
PR coming your way then =)

**Comment by bslatkin** [comment]
Oh and I meant to add: There are two ways to do it:

1. As a read-time change, so you just allow all builds to be public
2. As a write-time default, so all builds default to public

I see benefits to each approach. I like (1) because if you change your mind you don't have to change your DB, just flip a flag and you're done. The problem with (1) is it'll still say "private" next to your builds. I guess you could also override that property accessor on the model to take the global setting into account? Or hide the column?

**Comment by elsigh** [comment]
I'm fine if all builds default to public but I just have to click Settings to update that value (that's what I'm planning this first PR is gonna do)

**Comment by elsigh** [comment]
https://github.com/bslatkin/dpxdt/pull/141 =)
